apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-deployment
  labels:
    app: netflix-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-app
  template:
    metadata:
      labels:
        app: netflix-app
    spec:
      containers:
      - name: my-netflix-app
        image: netflix:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata:
  name: my-service
  labels:
    app: netflix-app
spec:
  selector:
    app: netflix-app
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer